token: ""
url: "https://lichess.org/"
engine:
  dir: ""
  name: ""
  protocol: "uci"
challenge:
  accept_bot: true
  variants:
    - standard
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  modes:
    - casual
    - rated
